version: '3.8'

services:
  database:
    image: mysql:8.0.24
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=cluster_flex
      - TZ=Asia/Taipei
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=NqEak1gc

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq-container
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  spring_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: eureka
    container_name: eureka-container
    ports:
      - 8761:8761
    # depends_on:
    #   - mysql
    #   - redis
    #   - rabbitmq
    # environment:
    #   - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cluster_flex?useSSL=false&allowPublicKeyRetrieval=true
    #   - SPRING_DATASOURCE_USERNAME=root
    #   - SPRING_DATASOURCE_PASSWORD=123456
    #   - SPRING_REDIS_HOST=redis
    #   - SPRING_REDIS_PORT=6379
    #   - SPRING_REDIS_PASSWORD=NqEak1gc
    #   - SPRING_RABBITMQ_HOST=rabbitmq
    #   - SPRING_RABBITMQ_PORT=5672
    #   - SPRING_RABBITMQ_USERNAME=guest
    #   - SPRING_RABBITMQ_PASSWORD=guest
